export const CLIENT_EVENT = 'CLIENT_EVENT';
export const CLIENT_EVENT_REPLY = 'CLIENT_EVENT_REPLY';
export const INVALID_CLIENT_EVENT = 'INVALID_CLIENT_EVENT';

export const BROWSER_EVENT = 'BROWSER_EVENT';
export const BROWSER_EVENT_REPLY = 'BROWSER_EVENT_REPLY';

export const AUTH_EVENT = 'AUTH_EVENT';
export const AUTH_EVENT_REPLY = 'AUTH_EVENT_REPLY';

export const EDITOR_EVENT = 'EDITOR_EVENT';
export const EDITOR_EVENT_REPLY = 'EDITOR_EVENT_REPLY';