export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const FETCH_OWNER_DATA_INIT = 'FETCH_OWNER_DATA_INIT';
export const FETCH_OWNER_DATA_START = 'FETCH_OWNER_DATA_START';
export const FETCH_OWNER_DATA_SUCCESS = 'FETCH_OWNER_DATA_SUCCESS';
export const FETCH_OWNER_DATA_FAIL = 'FETCH_OWNER_DATA_FAIL';

export const FETCH_OWNER_REPO_INIT = 'FETCH_OWNER_REPO_INIT';
export const FETCH_OWNER_REPO_START = 'FETCH_OWNER_REPO_START';
export const FETCH_OWNER_REPO_SUCCESS = 'FETCH_OWNER_REPO_SUCCESS';
export const FETCH_OWNER_REPO_FAIL = 'FETCH_OWNER_REPO_FAIL';

export const FETCH_USER_DATA_INIT = 'FETCH_USER_DATA_INIT';
export const FETCH_USER_DATA_START = 'FETCH_USER_DATA_START';
export const FETCH_USER_DATA_SUCCESS = 'FETCH_USER_DATA_SUCCESS';
export const FETCH_USER_DATA_FAIL = 'FETCH_USER_DATA_FAIL';

export const FETCH_USER_REPO_INIT = 'FETCH_USER_REPO_INIT';
export const FETCH_USER_REPO_START = 'FETCH_USER_REPO_START';
export const FETCH_USER_REPO_SUCCESS = 'FETCH_USER_REPO_SUCCESS';
export const FETCH_USER_REPO_FAIL = 'FETCH_USER_DATA_FAIL';

export const SEARCH_USER_LIST_INIT = 'SEARCH_USER_LIST_INIT';
export const SEARCH_USER_LIST_START = 'SEARCH_USER_LIST_START';
export const SEARCH_USER_LIST_SUCCESS = 'SEARCH_USER_LIST_SUCCESS';
export const SEARCH_USER_LIST_FAIL = 'SEARCH_USER_LIST_FAIL';

export const CREATE_OWNER_REPO_INIT = 'CREATE_OWNER_REPO_INIT';
export const CREATE_OWNER_REPO_START = 'CREATE_OWNER_REPO_START';
export const CREATE_OWNER_REPO_SUCCESS = 'CREATE_OWNER_REPO_SUCCESS';
export const CREATE_OWNER_REPO_FAIL = 'CREATE_OWNER_REPO_FAIL';

export const OPEN_CHROME_INIT = 'OPEN_CHROME_INIT';
export const OPEN_CHROME_START = 'OPEN_CHROME_START';
export const OPEN_CHROME_SUCCESS = 'OPEN_CHROME_SUCCESS';
export const OPEN_CHROME_FAIL = 'OPEN_CHROME_FAIL';

export const OPEN_VSCODE_INIT = 'OPEN_VSCODE_INIT';
export const OPEN_VSCODE_START = 'OPEN_VSCODE_START';
export const OPEN_VSCODE_SUCCESS = 'OPEN_VSCODE_SUCCESS';
export const OPEN_VSCODE_FAIL = 'OPEN_VSCODE_FAIL';

export const SAVE_DATA_LOCALSTORAGE_INIT = 'SAVE_DATA_LOCALSTORAGE_INIT';
export const SAVE_DATA_LOCALSTORAGE_START = 'SAVE_DATA_LOCALSTORAGE_START';
export const SAVE_DATA_LOCALSTORAGE_FAIL = 'SAVE_DATA_LOCALSTORAGE_FAIL';
export const SAVE_DATA_LOCALSTORAGE_SUCCESS = 'SAVE_DATA_LOCALSTORAGE_SUCCESS';

export const FETCH_DATA_LOCALSTORAGE_INIT = 'FETCH_DATA_LOCALSTORAGE_INIT';
export const FETCH_DATA_LOCALSTORAGE_START = 'FETCH_DATA_LOCALSTORAGE_START'; 
export const FETCH_DATA_LOCALSTORAGE_SUCCESS = 'FETCH_DATA_LOCALSTORAGE_SUCCESS';
export const FETCH_DATA_LOCALSTORAGE_FAIL = 'FETCH_DATA_LOCALSTORAGE_FAIL';

export const DELETE_DATA_LOCALSTORAGE_INIT = 'DELETE_DATA_LOCALSTORAGE_INIT';
export const DELETE_DATA_LOCALSTORAGE_START = 'DELETE_DATA_LOCALSTORAGE_START';
export const DELETE_DATA_LOCALSTORAGE_SUCCESS = 'DELETE_DATA_LOCALSTORAGE_SUCCESS';
export const DELETE_DATA_LOCALSTORAGE_FAIL = 'DELETE_DATA_LOCALSTORAGE_FAIL';